### ISSUE TITLE
Not sure why it's not working

### ISSUE THREAD

**Issue by LipJ01** [MrGVSV/obsidian-github-embeds#4] opened 2023-11-01 14:27 UTC
Hi there, I've just installed this extension and have made a personal access token as per instructions.
I've then tried making a link to GH repo file and pull request... No pop up or embedded thing appears.
I've tried restarting obsidian. I'm not sure how to debug further. Is there a way I can see that the extension is happy with the personal access token? Is there something I've missed as to how to trigger the embedded bit.

Thanks again for making this extension. I believe when it works it will be an elegant solution.

EDIT/TLDR: I was being scilly. I wasn't in read mode.

**Comment by LipJ01** [comment] 2023-11-01 14:36
Okay, progress made (through using reading mode), I now have a thing popping up... unfortunately it has an error.

Error loading GitHub embedInvalidCharacterError: Failed to execute 'atob
' on 'Window': The string to be decoded is not correctly encoded.


<img width="780" alt="Screenshot 2023-11-01 at 14 34 02" src="https://github.com/MrGVSV/obsidian-github-embeds/assets/12955915/2e643281-8610-4979-800b-418004f4f85f">

Still not sure how to debug from here.

**Comment by MrGVSV** [comment] 2023-11-01 19:14
> Okay, progress made (through using reading mode), I now have a thing popping up... unfortunately it has an error.
> 
> Error loading GitHub embedInvalidCharacterError: Failed to execute 'atob ' on 'Window': The string to be decoded is not correctly encoded.
> 
> <img alt="Screenshot 2023-11-01 at 14 34 02" width="780" src="https://user-images.githubusercontent.com/12955915/279705179-2e643281-8610-4979-800b-418004f4f85f.png">
> Still not sure how to debug from here.

Is this a private repo? You might need to setup your token to access private repos if so.

**Comment by ndrezn** [comment] 2023-11-07 22:00
This issue should probably be closed, but I'll mention that it should be made clear in the Settings page (not just the main page) that you must be in "reader" mode for previews to show; this wasn't obvious for me...

**Comment by MrGVSV** [comment] 2023-11-08 02:12
> This issue should probably be closed, but I'll mention that it should be made clear in the Settings page (not just the main page) that you must be in "reader" mode for previews to show; this wasn't obvious for me...

Good call. Could you make an issue for that? I'll try to make that more clear until we support editor mode!

Also, @LipJ01 I'm going to close this issue for now. Let me know if the problem is still happening after adjusting your token's permissions and we can reopen!

**Closed** 2023-11-08 02:13 UTC
